yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreatedModel
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200,
                             verbose_name='Название группы',
                             help_text='Указать название группы')
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name='Описание',
                                   help_text='Описание группы')

    class Meta:
        verbose_name = 'Группу'
        verbose_name_plural = 'Группы'
        ordering = ('title',)

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField('Текст поста',
                            help_text='Введите текст поста')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              related_name='posts',
                              blank=True, null=True,
                              verbose_name='Группа',
                              help_text=' Выберите группу')
    image = models.ImageField('Картинка',
                              upload_to='posts/',
                              blank=True,
                              help_text='Картинка')

    class Meta:
        ordering = ['-pub_date', 'author']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name='Текс поста',
                             blank=True,
                             null=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments',
                               verbose_name='Автор')
    text = models.TextField(verbose_name='Комментарий',
                            help_text='Напишите комментарий')

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(User,
                             related_name='follower',
                             on_delete=models.CASCADE)
    author = models.ForeignKey(User,
                               related_name='following',
                               on_delete=models.CASCADE)

    class Meta:
        ordering = ('-author',)
        verbose_name = 'Лента автора'
        verbose_name_plural = 'Лента авторов'
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'], name='unique_members')]

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = "Группа не выбрана"

    class Meta:
        model = Post
        help_texts = {'group': 'Выберите группу',
                      'text': 'Введите ссообщение',
                      'image': 'Изображение'}
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm, CommentForm
from .models import Post, Group, Follow


def get_page_context(queryset, request):
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {'page_obj': page_obj}


def index(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    context.update(get_page_context(Post.objects.all(), request))
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    context = {
        'group': group,
        'posts': posts,
    }
    context.update(get_page_context(Post.objects.filter(group=group), request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_sum = author.posts.count()
    post_list = author.posts.select_related('group').all()
    following = (request.user.is_authenticated
                 and Follow.objects.filter(
                     user=request.user,
                     author=author).exists())
    context = {'author': author,
               'posts_sum': posts_sum,
               'post_list': post_list,
               'following': following,
               }
    context.update(get_page_context(
        author.posts.select_related('group').all(), request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    post_count = post.author.posts.count()
    context = {'post': post,
               'form': form,
               'comments': comments,
               'post_count': post_count,
               }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', username=request.user)
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'posts/create_post.html', context)


def post_edit(request, post_id):
    poster = get_object_or_404(Post, pk=post_id)
    is_edit = 'is_edit'
    if request.method == 'GET':
        if request.user.pk is not poster.author_id:
            return redirect('posts:post_detail', post_id=poster.id)
        form = PostForm(instance=poster)

    if request.method == 'POST':
        form = PostForm(request.POST or None,
                        files=request.FILES or None,
                        instance=poster)
        if form.is_valid():
            form.save()
        return redirect('posts:post_detail', post_id=poster.id)

    context = {'form': form,
               'post': poster,
               'is_edit': is_edit,
               }

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    Follow.objects.filter(user=user, author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load user_filters %}
<main>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        {% if not post %} Новый пост
                        {% else %} Редaктирование поста
                        {% endif %}
                    </div>
                    <div class="card-body">

                        {% for error in form.errors %}
                        <div classs="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}

                        <form method="post" enctype="multipart/form-data" action=
                                {% if post %}
                        "{% url 'posts:post_edit' post.id %}"
                        {% else %}
                        "{% url 'posts:post_create' %}"
                        {% endif %}>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row my-3">
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                <span class="required text-danger">*</span>
                                {% endif %}
                            </label>
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                            <small
                                    id="{{ field.id_for_label }}-help"
                                    class="form-text text-muted"
                            >
                                {{ field.help_text|safe }}
                            </small>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                Сохранить
                                {% else %}
                                Добавить
                                {% endif %}
                            </button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}
{% block title %}Лента пользователя{% endblock %}
{% block content %}
<h1>Лента пользователя</h1>
{% for post in page_obj %}
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
        {{ post.text|truncatewords:50 }}
    </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        {% include 'posts/includes/switcher.html' with follow=True %}
            {% if forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group-article.html
{% load thumbnail %}
<article>
  <ul>
    {% if author_link %}
      <li>
        Автор: {{ post.author.username }}
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
    {% endif %}
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a></p>
  {% if post.group %}
    {% if profile_link_flag %}
      <p><a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a></p>
    {% endif %}
  {% endif %}
</article>
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block content %}
<main>
    <h1>{{ group }}</h1>
    <p>{{ group.description }}</p>
    {% for post in posts %}
    <article>
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        <p>
            {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </article>
        {% if post.group %}
        <a href="{% url 'posts:group_list' group.slug %}">все записи группы</a>
        {% endif %}
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
</main>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% cache 20 index_page %}
<h1>Последние обновления на сайте</h1>
{% for p in posts %}
    <ul>
        <li>
            Автор: {{ p.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ p.pub_date|date:"d E Y" }}
        </li>
    </ul>
    {% thumbnail p.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
        {{ p.text|truncatewords:50 }}
    </p>
        <a href="{% url 'posts:post_detail' p.pk %}">подробная информация</a>
    {% if p.group %}
        <a href="{% url 'posts:group_list' p.group.slug %}">Все записи группы</a>
    {% endif %}
    {% include 'posts/includes/switcher.html' with index=True %}
        {% for post in page_obj %}
            {% if forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endfor %}
{% endcache %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
<main>
    <div class="container py-5">
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                    <li class="list-group-item">
                        Группа: {{ post.group }}
                        {% if post.group %}
                        <a href="{% url 'posts:group_list' post.group.slug %}">
                            <p>все записи группы</p>
                        </a>
                        {% endif %}
                    </li>
                    <li class="list-group-item">
                        Автор: {{ post.author }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора:<span>{{ post_count }}</span>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' post.author.username %}">
                            все посты пользователя
                        </a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my_2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>
                    {{ post.text }}
                </p>
                {% if request.user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
                    редактировать запись
                </a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'posts:profile' post.author.username %}">
                    редактировать запись
                </a>
                {% endif %}
                <div class="card my-4">
                    {% include 'posts/comments.html' %}
                </div>
            </article>
        </div>
    </div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group.slug }}{% endblock %}
{% block content %}
<div class="mb-5">
    <h1>Все посты пользователя: {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ posts_sum }} </h3>
        {% if following %}
            <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
                Отписаться
            </a>
        {% else %}
            <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
                Подписаться
            </a>
        {% endif %}
</div>
    {% for post in post_list%}
    <article>
        <ul>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my_2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </article>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}